language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t robturtle/client-test ./client

script:
  - docker run -e CI=true robturtle/client-test npm test

after_success:
  - ./scripts/deploy

# NOTE: AWS was deleted to avoid the bill.
# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-1"
#   app: "udemy-docker"
#   env: "UdemyDocker-env"
#   bucket_name: "elasticbeanstalk-us-west-1-402467898701"
#   bucket_path: "udemy-docker"
#   on:
#     branch: master
#   access_key_id:
#     secure: "$AWS_ACCESS_KEY"
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"
