apiVersion: skaffold/v1beta1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: robturtle/udemy-docker-client
      context: ./client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .

    - image: robturtle/udemy-docker-server
      context: ./server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .

    - image: robturtle/udemy-docker-worker
      context: ./worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .

deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yml
      - k8s/server-deployment.yml
      - k8s/worker-deployment.yml
