apiVersion: skaffold/v1beta1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: robturtle/udemy-docker-client
      context: ./client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yml
