#!/bin/bash

TAG=$1

function build() {
  image="robturtle/udemy-docker-$1"

  if test $TAG; then
    tag=$image:$TAG
  else
    tag=$image:`cat ./$1/version`
  fi

  docker build -t $tag -t $image:latest ./$1
  docker push $tag
  docker push $image:latest
}

if echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin; then
  build client
  build server
  build worker
else
  echo '[ERROR] login to DockerHub failed!'
  exit 1
fi
