#!/bin/bash

TAG=$1

function docker_tag_exists() {
  curl --silent -f -lSL https://index.docker.io/v1/repositories/$1/tags/$2 > /dev/null
}

function build() {
  image="robturtle/udemy-docker-$1"

  if test $TAG; then
    tag=$image:$TAG
  else
    tag=$image:`cat ./$1/version`
  fi

  if docker_tag_exists $tag; then
    echo "DockerHub tag $TAG already exists. Skipping build."
  else
    docker build -t $tag -t $image:latest ./$1
    docker push $tag
    docker push $image:latest
  fi
}

if echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin; then
  build client
  build server
  build worker
else
  echo '[ERROR] login to DockerHub failed!'
  exit 1
fi
