#!/bin/bash

SHA=`git rev-parse HEAD`

function deploy() {
  kubectl set image deployments/$1-deployment $1="robturtle/udemy-docker-$1:$SHA"
}

if ./scripts/build $SHA; then

  kubectl apply -f ./k8s

  deploy client
  deploy server
  deploy worker
fi
